//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2015/12/24 22:50:19
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationData in the schema.
    /// </summary>
    public partial class ApplicationData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for InfoesSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Infoes> InfoesSet
        {
            get
            {
                if ((this._InfoesSet == null))
                {
                    this._InfoesSet = base.CreateQuery<Infoes>("InfoesSet");
                }
                return this._InfoesSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Infoes> _InfoesSet;
        /// <summary>
        /// There are no comments for SocialRels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SocialRel> SocialRels
        {
            get
            {
                if ((this._SocialRels == null))
                {
                    this._SocialRels = base.CreateQuery<SocialRel>("SocialRels");
                }
                return this._SocialRels;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SocialRel> _SocialRels;
        /// <summary>
        /// There are no comments for InfoesSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInfoesSet(Infoes infoes)
        {
            base.AddObject("InfoesSet", infoes);
        }
        /// <summary>
        /// There are no comments for SocialRels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSocialRels(SocialRel socialRel)
        {
            base.AddObject("SocialRels", socialRel);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"Infoes\"><Key><PropertyRef Name=\"Id\" /></Key><P" +
                "roperty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPat" +
                "tern=\"Identity\" /><Property Name=\"PID\" Type=\"Edm.String\" Nullable=\"false\" MaxLen" +
                "gth=\"255\" /><Property Name=\"Photo\" Type=\"Edm.Binary\" MaxLength=\"Max\" /><Property" +
                " Name=\"Name\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Sex\" Type=\"Edm." +
                "String\" MaxLength=\"255\" /><Property Name=\"BirthDate\" Type=\"Edm.DateTime\" /><Prop" +
                "erty Name=\"Nation\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Native\" T" +
                "ype=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Politics\" Type=\"Edm.String\" M" +
                "axLength=\"255\" /><Property Name=\"Health\" Type=\"Edm.String\" MaxLength=\"255\" /><Pr" +
                "operty Name=\"ProJob\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Special" +
                "ity\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"BirthPlace\" Type=\"Edm.S" +
                "tring\" MaxLength=\"255\" /><Property Name=\"WorkDate\" Type=\"Edm.DateTime\" /><Proper" +
                "ty Name=\"PartyDate\" Type=\"Edm.DateTime\" /><Property Name=\"Duty\" Type=\"Edm.String" +
                "\" MaxLength=\"255\" /><Property Name=\"Rank\" Type=\"Edm.String\" MaxLength=\"255\" /><P" +
                "roperty Name=\"JobTitle\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Majo" +
                "r\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Character\" Type=\"Edm.Stri" +
                "ng\" MaxLength=\"255\" /><Property Name=\"Interest\" Type=\"Edm.String\" MaxLength=\"255" +
                "\" /><Property Name=\"XianRen\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=" +
                "\"NiRen\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"NiMian\" Type=\"Edm.St" +
                "ring\" MaxLength=\"255\" /><Property Name=\"WorkExp\" Type=\"Edm.String\" MaxLength=\"25" +
                "5\" /><Property Name=\"RewardPunish\" Type=\"Edm.String\" MaxLength=\"255\" /><Property" +
                " Name=\"Exam\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Reason\" Type=\"E" +
                "dm.String\" MaxLength=\"255\" /><Property Name=\"FullEdu\" Type=\"Edm.String\" MaxLengt" +
                "h=\"255\" /><Property Name=\"FUniMajor\" Type=\"Edm.String\" MaxLength=\"255\" /><Proper" +
                "ty Name=\"PartEdu\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"PUniMajor\"" +
                " Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"CreatedBy\" Type=\"Edm.String" +
                "\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Proper" +
                "ty Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modifie" +
                "d\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nul" +
                "lable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed" +
                "\" /><NavigationProperty Name=\"SocialRel\" Relationship=\"LightSwitchApplication.So" +
                "cialRel_Infoes\" ToRole=\"SocialRel\" FromRole=\"Infoes\" /></EntityType><EntityType " +
                "Name=\"SocialRel\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"E" +
                "dm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" /><Proper" +
                "ty Name=\"RelTitle\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Propert" +
                "y Name=\"RelName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property " +
                "Name=\"RelBirthDate\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Proper" +
                "ty Name=\"RelParty\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"RelComJob" +
                "\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"ChuJiRel_ChuJiInfoes1\" Typ" +
                "e=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\" Ma" +
                "xLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Property N" +
                "ame=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modified\" T" +
                "ype=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullabl" +
                "e=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\" />" +
                "<NavigationProperty Name=\"Infoes\" Relationship=\"LightSwitchApplication.SocialRel" +
                "_Infoes\" ToRole=\"Infoes\" FromRole=\"SocialRel\" /></EntityType><Association Name=\"" +
                "SocialRel_Infoes\"><End Role=\"Infoes\" Type=\"LightSwitchApplication.Infoes\" Multip" +
                "licity=\"1\" /><End Role=\"SocialRel\" Type=\"LightSwitchApplication.SocialRel\" Multi" +
                "plicity=\"*\" /><ReferentialConstraint><Principal Role=\"Infoes\"><PropertyRef Name=" +
                "\"Id\" /></Principal><Dependent Role=\"SocialRel\"><PropertyRef Name=\"ChuJiRel_ChuJi" +
                "Infoes1\" /></Dependent></ReferentialConstraint></Association><EntityContainer Na" +
                "me=\"ApplicationData\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"InfoesSe" +
                "t\" EntityType=\"LightSwitchApplication.Infoes\" /><EntitySet Name=\"SocialRels\" Ent" +
                "ityType=\"LightSwitchApplication.SocialRel\" /><AssociationSet Name=\"SocialRel_Inf" +
                "oes\" Association=\"LightSwitchApplication.SocialRel_Infoes\"><End Role=\"Infoes\" En" +
                "titySet=\"InfoesSet\" /><End Role=\"SocialRel\" EntitySet=\"SocialRels\" /></Associati" +
                "onSet><FunctionImport Name=\"Microsoft_LightSwitch_GetCanInformation\" ReturnType=" +
                "\"Edm.String\" m:HttpMethod=\"GET\"><Parameter Name=\"dataServiceMembers\" Type=\"Edm.S" +
                "tring\" Mode=\"In\" /></FunctionImport></EntityContainer></Schema></edmx:DataServic" +
                "es></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Infoes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("InfoesSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Infoes : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Infoes object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="pID">Initial value of PID.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Infoes CreateInfoes(int ID, string pID, byte[] rowVersion)
        {
            Infoes infoes = new Infoes();
            infoes.Id = ID;
            infoes.PID = pID;
            infoes.RowVersion = rowVersion;
            return infoes;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property PID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PID
        {
            get
            {
                return this._PID;
            }
            set
            {
                this.OnPIDChanging(value);
                if (object.Equals(this.PID, value))
                {
                    return;
                }
                this._PID = value;
                this.OnPIDChanged();
                this.OnPropertyChanged("PID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PID;
        partial void OnPIDChanging(string value);
        partial void OnPIDChanged();
        /// <summary>
        /// There are no comments for Property Photo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Photo
        {
            get
            {
                if ((this._Photo != null))
                {
                    return ((byte[])(this._Photo.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPhotoChanging(value);
                if (object.Equals(this.Photo, value))
                {
                    return;
                }
                this._Photo = value;
                this.OnPhotoChanged();
                this.OnPropertyChanged("Photo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Photo;
        partial void OnPhotoChanging(byte[] value);
        partial void OnPhotoChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Sex in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sex
        {
            get
            {
                return this._Sex;
            }
            set
            {
                this.OnSexChanging(value);
                if (object.Equals(this.Sex, value))
                {
                    return;
                }
                this._Sex = value;
                this.OnSexChanged();
                this.OnPropertyChanged("Sex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sex;
        partial void OnSexChanging(string value);
        partial void OnSexChanged();
        /// <summary>
        /// There are no comments for Property BirthDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> BirthDate
        {
            get
            {
                return this._BirthDate;
            }
            set
            {
                this.OnBirthDateChanging(value);
                if (object.Equals(this.BirthDate, value))
                {
                    return;
                }
                this._BirthDate = value;
                this.OnBirthDateChanged();
                this.OnPropertyChanged("BirthDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _BirthDate;
        partial void OnBirthDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnBirthDateChanged();
        /// <summary>
        /// There are no comments for Property Nation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nation
        {
            get
            {
                return this._Nation;
            }
            set
            {
                this.OnNationChanging(value);
                if (object.Equals(this.Nation, value))
                {
                    return;
                }
                this._Nation = value;
                this.OnNationChanged();
                this.OnPropertyChanged("Nation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nation;
        partial void OnNationChanging(string value);
        partial void OnNationChanged();
        /// <summary>
        /// There are no comments for Property Native in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Native
        {
            get
            {
                return this._Native;
            }
            set
            {
                this.OnNativeChanging(value);
                if (object.Equals(this.Native, value))
                {
                    return;
                }
                this._Native = value;
                this.OnNativeChanged();
                this.OnPropertyChanged("Native");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Native;
        partial void OnNativeChanging(string value);
        partial void OnNativeChanged();
        /// <summary>
        /// There are no comments for Property Politics in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Politics
        {
            get
            {
                return this._Politics;
            }
            set
            {
                this.OnPoliticsChanging(value);
                if (object.Equals(this.Politics, value))
                {
                    return;
                }
                this._Politics = value;
                this.OnPoliticsChanged();
                this.OnPropertyChanged("Politics");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Politics;
        partial void OnPoliticsChanging(string value);
        partial void OnPoliticsChanged();
        /// <summary>
        /// There are no comments for Property Health in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Health
        {
            get
            {
                return this._Health;
            }
            set
            {
                this.OnHealthChanging(value);
                if (object.Equals(this.Health, value))
                {
                    return;
                }
                this._Health = value;
                this.OnHealthChanged();
                this.OnPropertyChanged("Health");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Health;
        partial void OnHealthChanging(string value);
        partial void OnHealthChanged();
        /// <summary>
        /// There are no comments for Property ProJob in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProJob
        {
            get
            {
                return this._ProJob;
            }
            set
            {
                this.OnProJobChanging(value);
                if (object.Equals(this.ProJob, value))
                {
                    return;
                }
                this._ProJob = value;
                this.OnProJobChanged();
                this.OnPropertyChanged("ProJob");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProJob;
        partial void OnProJobChanging(string value);
        partial void OnProJobChanged();
        /// <summary>
        /// There are no comments for Property Speciality in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Speciality
        {
            get
            {
                return this._Speciality;
            }
            set
            {
                this.OnSpecialityChanging(value);
                if (object.Equals(this.Speciality, value))
                {
                    return;
                }
                this._Speciality = value;
                this.OnSpecialityChanged();
                this.OnPropertyChanged("Speciality");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Speciality;
        partial void OnSpecialityChanging(string value);
        partial void OnSpecialityChanged();
        /// <summary>
        /// There are no comments for Property BirthPlace in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BirthPlace
        {
            get
            {
                return this._BirthPlace;
            }
            set
            {
                this.OnBirthPlaceChanging(value);
                if (object.Equals(this.BirthPlace, value))
                {
                    return;
                }
                this._BirthPlace = value;
                this.OnBirthPlaceChanged();
                this.OnPropertyChanged("BirthPlace");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BirthPlace;
        partial void OnBirthPlaceChanging(string value);
        partial void OnBirthPlaceChanged();
        /// <summary>
        /// There are no comments for Property WorkDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> WorkDate
        {
            get
            {
                return this._WorkDate;
            }
            set
            {
                this.OnWorkDateChanging(value);
                if (object.Equals(this.WorkDate, value))
                {
                    return;
                }
                this._WorkDate = value;
                this.OnWorkDateChanged();
                this.OnPropertyChanged("WorkDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _WorkDate;
        partial void OnWorkDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnWorkDateChanged();
        /// <summary>
        /// There are no comments for Property PartyDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> PartyDate
        {
            get
            {
                return this._PartyDate;
            }
            set
            {
                this.OnPartyDateChanging(value);
                if (object.Equals(this.PartyDate, value))
                {
                    return;
                }
                this._PartyDate = value;
                this.OnPartyDateChanged();
                this.OnPropertyChanged("PartyDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _PartyDate;
        partial void OnPartyDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPartyDateChanged();
        /// <summary>
        /// There are no comments for Property Duty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Duty
        {
            get
            {
                return this._Duty;
            }
            set
            {
                this.OnDutyChanging(value);
                if (object.Equals(this.Duty, value))
                {
                    return;
                }
                this._Duty = value;
                this.OnDutyChanged();
                this.OnPropertyChanged("Duty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Duty;
        partial void OnDutyChanging(string value);
        partial void OnDutyChanged();
        /// <summary>
        /// There are no comments for Property Rank in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Rank
        {
            get
            {
                return this._Rank;
            }
            set
            {
                this.OnRankChanging(value);
                if (object.Equals(this.Rank, value))
                {
                    return;
                }
                this._Rank = value;
                this.OnRankChanged();
                this.OnPropertyChanged("Rank");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Rank;
        partial void OnRankChanging(string value);
        partial void OnRankChanged();
        /// <summary>
        /// There are no comments for Property JobTitle in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string JobTitle
        {
            get
            {
                return this._JobTitle;
            }
            set
            {
                this.OnJobTitleChanging(value);
                if (object.Equals(this.JobTitle, value))
                {
                    return;
                }
                this._JobTitle = value;
                this.OnJobTitleChanged();
                this.OnPropertyChanged("JobTitle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _JobTitle;
        partial void OnJobTitleChanging(string value);
        partial void OnJobTitleChanged();
        /// <summary>
        /// There are no comments for Property Major in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Major
        {
            get
            {
                return this._Major;
            }
            set
            {
                this.OnMajorChanging(value);
                if (object.Equals(this.Major, value))
                {
                    return;
                }
                this._Major = value;
                this.OnMajorChanged();
                this.OnPropertyChanged("Major");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Major;
        partial void OnMajorChanging(string value);
        partial void OnMajorChanged();
        /// <summary>
        /// There are no comments for Property Character in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Character
        {
            get
            {
                return this._Character;
            }
            set
            {
                this.OnCharacterChanging(value);
                if (object.Equals(this.Character, value))
                {
                    return;
                }
                this._Character = value;
                this.OnCharacterChanged();
                this.OnPropertyChanged("Character");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Character;
        partial void OnCharacterChanging(string value);
        partial void OnCharacterChanged();
        /// <summary>
        /// There are no comments for Property Interest in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Interest
        {
            get
            {
                return this._Interest;
            }
            set
            {
                this.OnInterestChanging(value);
                if (object.Equals(this.Interest, value))
                {
                    return;
                }
                this._Interest = value;
                this.OnInterestChanged();
                this.OnPropertyChanged("Interest");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Interest;
        partial void OnInterestChanging(string value);
        partial void OnInterestChanged();
        /// <summary>
        /// There are no comments for Property XianRen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string XianRen
        {
            get
            {
                return this._XianRen;
            }
            set
            {
                this.OnXianRenChanging(value);
                if (object.Equals(this.XianRen, value))
                {
                    return;
                }
                this._XianRen = value;
                this.OnXianRenChanged();
                this.OnPropertyChanged("XianRen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _XianRen;
        partial void OnXianRenChanging(string value);
        partial void OnXianRenChanged();
        /// <summary>
        /// There are no comments for Property NiRen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NiRen
        {
            get
            {
                return this._NiRen;
            }
            set
            {
                this.OnNiRenChanging(value);
                if (object.Equals(this.NiRen, value))
                {
                    return;
                }
                this._NiRen = value;
                this.OnNiRenChanged();
                this.OnPropertyChanged("NiRen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NiRen;
        partial void OnNiRenChanging(string value);
        partial void OnNiRenChanged();
        /// <summary>
        /// There are no comments for Property NiMian in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NiMian
        {
            get
            {
                return this._NiMian;
            }
            set
            {
                this.OnNiMianChanging(value);
                if (object.Equals(this.NiMian, value))
                {
                    return;
                }
                this._NiMian = value;
                this.OnNiMianChanged();
                this.OnPropertyChanged("NiMian");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NiMian;
        partial void OnNiMianChanging(string value);
        partial void OnNiMianChanged();
        /// <summary>
        /// There are no comments for Property WorkExp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WorkExp
        {
            get
            {
                return this._WorkExp;
            }
            set
            {
                this.OnWorkExpChanging(value);
                if (object.Equals(this.WorkExp, value))
                {
                    return;
                }
                this._WorkExp = value;
                this.OnWorkExpChanged();
                this.OnPropertyChanged("WorkExp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WorkExp;
        partial void OnWorkExpChanging(string value);
        partial void OnWorkExpChanged();
        /// <summary>
        /// There are no comments for Property RewardPunish in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RewardPunish
        {
            get
            {
                return this._RewardPunish;
            }
            set
            {
                this.OnRewardPunishChanging(value);
                if (object.Equals(this.RewardPunish, value))
                {
                    return;
                }
                this._RewardPunish = value;
                this.OnRewardPunishChanged();
                this.OnPropertyChanged("RewardPunish");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RewardPunish;
        partial void OnRewardPunishChanging(string value);
        partial void OnRewardPunishChanged();
        /// <summary>
        /// There are no comments for Property Exam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Exam
        {
            get
            {
                return this._Exam;
            }
            set
            {
                this.OnExamChanging(value);
                if (object.Equals(this.Exam, value))
                {
                    return;
                }
                this._Exam = value;
                this.OnExamChanged();
                this.OnPropertyChanged("Exam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Exam;
        partial void OnExamChanging(string value);
        partial void OnExamChanged();
        /// <summary>
        /// There are no comments for Property Reason in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reason
        {
            get
            {
                return this._Reason;
            }
            set
            {
                this.OnReasonChanging(value);
                if (object.Equals(this.Reason, value))
                {
                    return;
                }
                this._Reason = value;
                this.OnReasonChanged();
                this.OnPropertyChanged("Reason");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reason;
        partial void OnReasonChanging(string value);
        partial void OnReasonChanged();
        /// <summary>
        /// There are no comments for Property FullEdu in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FullEdu
        {
            get
            {
                return this._FullEdu;
            }
            set
            {
                this.OnFullEduChanging(value);
                if (object.Equals(this.FullEdu, value))
                {
                    return;
                }
                this._FullEdu = value;
                this.OnFullEduChanged();
                this.OnPropertyChanged("FullEdu");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FullEdu;
        partial void OnFullEduChanging(string value);
        partial void OnFullEduChanged();
        /// <summary>
        /// There are no comments for Property FUniMajor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FUniMajor
        {
            get
            {
                return this._FUniMajor;
            }
            set
            {
                this.OnFUniMajorChanging(value);
                if (object.Equals(this.FUniMajor, value))
                {
                    return;
                }
                this._FUniMajor = value;
                this.OnFUniMajorChanged();
                this.OnPropertyChanged("FUniMajor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FUniMajor;
        partial void OnFUniMajorChanging(string value);
        partial void OnFUniMajorChanged();
        /// <summary>
        /// There are no comments for Property PartEdu in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PartEdu
        {
            get
            {
                return this._PartEdu;
            }
            set
            {
                this.OnPartEduChanging(value);
                if (object.Equals(this.PartEdu, value))
                {
                    return;
                }
                this._PartEdu = value;
                this.OnPartEduChanged();
                this.OnPropertyChanged("PartEdu");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PartEdu;
        partial void OnPartEduChanging(string value);
        partial void OnPartEduChanged();
        /// <summary>
        /// There are no comments for Property PUniMajor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PUniMajor
        {
            get
            {
                return this._PUniMajor;
            }
            set
            {
                this.OnPUniMajorChanging(value);
                if (object.Equals(this.PUniMajor, value))
                {
                    return;
                }
                this._PUniMajor = value;
                this.OnPUniMajorChanged();
                this.OnPropertyChanged("PUniMajor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PUniMajor;
        partial void OnPUniMajorChanging(string value);
        partial void OnPUniMajorChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for SocialRel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SocialRel> SocialRel
        {
            get
            {
                this.@__SocialRel.EnsureValueInitialized();
                return this._SocialRel;
            }
            set
            {
                this._SocialRel = value;
                this.OnPropertyChanged("SocialRel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SocialRel> _SocialRel = new global::System.Data.Services.Client.DataServiceCollection<SocialRel>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.SocialRel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SocialRels")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class SocialRel : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SocialRel object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="relTitle">Initial value of RelTitle.</param>
        /// <param name="relName">Initial value of RelName.</param>
        /// <param name="relBirthDate">Initial value of RelBirthDate.</param>
        /// <param name="chuJiRel_ChuJiInfoes1">Initial value of ChuJiRel_ChuJiInfoes1.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SocialRel CreateSocialRel(int ID, string relTitle, string relName, string relBirthDate, int chuJiRel_ChuJiInfoes1, byte[] rowVersion)
        {
            SocialRel socialRel = new SocialRel();
            socialRel.Id = ID;
            socialRel.RelTitle = relTitle;
            socialRel.RelName = relName;
            socialRel.RelBirthDate = relBirthDate;
            socialRel.ChuJiRel_ChuJiInfoes1 = chuJiRel_ChuJiInfoes1;
            socialRel.RowVersion = rowVersion;
            return socialRel;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RelTitle in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RelTitle
        {
            get
            {
                return this._RelTitle;
            }
            set
            {
                this.OnRelTitleChanging(value);
                if (object.Equals(this.RelTitle, value))
                {
                    return;
                }
                this._RelTitle = value;
                this.OnRelTitleChanged();
                this.OnPropertyChanged("RelTitle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RelTitle;
        partial void OnRelTitleChanging(string value);
        partial void OnRelTitleChanged();
        /// <summary>
        /// There are no comments for Property RelName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RelName
        {
            get
            {
                return this._RelName;
            }
            set
            {
                this.OnRelNameChanging(value);
                if (object.Equals(this.RelName, value))
                {
                    return;
                }
                this._RelName = value;
                this.OnRelNameChanged();
                this.OnPropertyChanged("RelName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RelName;
        partial void OnRelNameChanging(string value);
        partial void OnRelNameChanged();
        /// <summary>
        /// There are no comments for Property RelBirthDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RelBirthDate
        {
            get
            {
                return this._RelBirthDate;
            }
            set
            {
                this.OnRelBirthDateChanging(value);
                if (object.Equals(this.RelBirthDate, value))
                {
                    return;
                }
                this._RelBirthDate = value;
                this.OnRelBirthDateChanged();
                this.OnPropertyChanged("RelBirthDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RelBirthDate;
        partial void OnRelBirthDateChanging(string value);
        partial void OnRelBirthDateChanged();
        /// <summary>
        /// There are no comments for Property RelParty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RelParty
        {
            get
            {
                return this._RelParty;
            }
            set
            {
                this.OnRelPartyChanging(value);
                if (object.Equals(this.RelParty, value))
                {
                    return;
                }
                this._RelParty = value;
                this.OnRelPartyChanged();
                this.OnPropertyChanged("RelParty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RelParty;
        partial void OnRelPartyChanging(string value);
        partial void OnRelPartyChanged();
        /// <summary>
        /// There are no comments for Property RelComJob in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RelComJob
        {
            get
            {
                return this._RelComJob;
            }
            set
            {
                this.OnRelComJobChanging(value);
                if (object.Equals(this.RelComJob, value))
                {
                    return;
                }
                this._RelComJob = value;
                this.OnRelComJobChanged();
                this.OnPropertyChanged("RelComJob");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RelComJob;
        partial void OnRelComJobChanging(string value);
        partial void OnRelComJobChanged();
        /// <summary>
        /// There are no comments for Property ChuJiRel_ChuJiInfoes1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ChuJiRel_ChuJiInfoes1
        {
            get
            {
                return this._ChuJiRel_ChuJiInfoes1;
            }
            set
            {
                this.OnChuJiRel_ChuJiInfoes1Changing(value);
                if (object.Equals(this.ChuJiRel_ChuJiInfoes1, value))
                {
                    return;
                }
                this._ChuJiRel_ChuJiInfoes1 = value;
                this.OnChuJiRel_ChuJiInfoes1Changed();
                this.OnPropertyChanged("ChuJiRel_ChuJiInfoes1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ChuJiRel_ChuJiInfoes1;
        partial void OnChuJiRel_ChuJiInfoes1Changing(int value);
        partial void OnChuJiRel_ChuJiInfoes1Changed();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Infoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Infoes Infoes
        {
            get
            {
                this.@__Infoes.EnsureValueInitialized();
                return this._Infoes;
            }
            set
            {
                Infoes previous = this.Infoes;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Infoes = null;
                    this.@__Infoes.OnValueSet();
                    previous.SocialRel.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.ChuJiRel_ChuJiInfoes1 = value.Id;
                    }
                    else
                    {
                        this.ChuJiRel_ChuJiInfoes1 = default(int);
                    }
                }
                this._Infoes = value;
                this.@__Infoes.OnValueSet();
                if ((value != null))
                {
                    value.@__SocialRel.Add(this);
                }
                this.___OnPropertyChanged("Infoes");
                this.OnPropertyChanged("Infoes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Infoes _Infoes;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
