//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Infoes
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Infoes :
        global::LightSwitchApplication.Infoes.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnPIDChanged()
        {
            this.___OnPropertyChanged("PID");
        }
        
        partial void OnPhotoChanged()
        {
            this.___OnPropertyChanged("Photo");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnSexChanged()
        {
            this.___OnPropertyChanged("Sex");
        }
        
        partial void OnBirthDateChanged()
        {
            this.___OnPropertyChanged("BirthDate");
        }
        
        partial void OnNationChanged()
        {
            this.___OnPropertyChanged("Nation");
        }
        
        partial void OnNativeChanged()
        {
            this.___OnPropertyChanged("Native");
        }
        
        partial void OnPoliticsChanged()
        {
            this.___OnPropertyChanged("Politics");
        }
        
        partial void OnHealthChanged()
        {
            this.___OnPropertyChanged("Health");
        }
        
        partial void OnProJobChanged()
        {
            this.___OnPropertyChanged("ProJob");
        }
        
        partial void OnSpecialityChanged()
        {
            this.___OnPropertyChanged("Speciality");
        }
        
        partial void OnBirthPlaceChanged()
        {
            this.___OnPropertyChanged("BirthPlace");
        }
        
        partial void OnWorkDateChanged()
        {
            this.___OnPropertyChanged("WorkDate");
        }
        
        partial void OnPartyDateChanged()
        {
            this.___OnPropertyChanged("PartyDate");
        }
        
        partial void OnDutyChanged()
        {
            this.___OnPropertyChanged("Duty");
        }
        
        partial void OnRankChanged()
        {
            this.___OnPropertyChanged("Rank");
        }
        
        partial void OnJobTitleChanged()
        {
            this.___OnPropertyChanged("JobTitle");
        }
        
        partial void OnMajorChanged()
        {
            this.___OnPropertyChanged("Major");
        }
        
        partial void OnCharacterChanged()
        {
            this.___OnPropertyChanged("Character");
        }
        
        partial void OnInterestChanged()
        {
            this.___OnPropertyChanged("Interest");
        }
        
        partial void OnXianRenChanged()
        {
            this.___OnPropertyChanged("XianRen");
        }
        
        partial void OnNiRenChanged()
        {
            this.___OnPropertyChanged("NiRen");
        }
        
        partial void OnNiMianChanged()
        {
            this.___OnPropertyChanged("NiMian");
        }
        
        partial void OnWorkExpChanged()
        {
            this.___OnPropertyChanged("WorkExp");
        }
        
        partial void OnRewardPunishChanged()
        {
            this.___OnPropertyChanged("RewardPunish");
        }
        
        partial void OnExamChanged()
        {
            this.___OnPropertyChanged("Exam");
        }
        
        partial void OnReasonChanged()
        {
            this.___OnPropertyChanged("Reason");
        }
        
        partial void OnFullEduChanged()
        {
            this.___OnPropertyChanged("FullEdu");
        }
        
        partial void OnFUniMajorChanged()
        {
            this.___OnPropertyChanged("FUniMajor");
        }
        
        partial void OnPartEduChanged()
        {
            this.___OnPropertyChanged("PartEdu");
        }
        
        partial void OnPUniMajorChanged()
        {
            this.___OnPropertyChanged("PUniMajor");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Infoes.DetailsClass.IImplementation.SocialRel
        {
            get
            {
                return this.SocialRel;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SocialRel> __SocialRel
        {
            get
            {
                if (this.___SocialRel == null)
                {
                    this.___SocialRel = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SocialRel>(
                        this,
                        "SocialRel",
                        () => this._SocialRel,
                        e => global::System.Object.Equals(e.ChuJiRel_ChuJiInfoes1, this.Id));
                }
                return this.___SocialRel;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SocialRel> ___SocialRel;
        
    }
    #endregion
    
    #region SocialRel
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SocialRel :
        global::LightSwitchApplication.SocialRel.DetailsClass.IImplementation
    {
        partial void OnChuJiRel_ChuJiInfoes1Changed()
        {
            this.___OnPropertyChanged("ChuJiRel_ChuJiInfoes1");
            this.___OnPropertyChanged("Infoes");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRelTitleChanged()
        {
            this.___OnPropertyChanged("RelTitle");
        }
        
        partial void OnRelNameChanged()
        {
            this.___OnPropertyChanged("RelName");
        }
        
        partial void OnRelBirthDateChanged()
        {
            this.___OnPropertyChanged("RelBirthDate");
        }
        
        partial void OnRelPartyChanged()
        {
            this.___OnPropertyChanged("RelParty");
        }
        
        partial void OnRelComJobChanged()
        {
            this.___OnPropertyChanged("RelComJob");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.SocialRel.DetailsClass.IImplementation.Infoes
        {
            get
            {
                return this.Infoes;
            }
            set
            {
                this.Infoes = (global::LightSwitchApplication.Implementation.Infoes)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Infoes> __Infoes
        {
            get
            {
                if (this.___Infoes == null)
                {
                    this.___Infoes = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Infoes>(
                        this,
                        "Infoes",
                        new string[] { "ChuJiRel_ChuJiInfoes1" },
                        e => global::System.Object.Equals(e.Id, this.ChuJiRel_ChuJiInfoes1),
                        () => this._Infoes,
                        e => this._Infoes = e);
                }
                return this.___Infoes;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Infoes> ___Infoes;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Infoes))
            {
                return new global::LightSwitchApplication.Implementation.Infoes();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SocialRel))
            {
                return new global::LightSwitchApplication.Implementation.SocialRel();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Infoes) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Infoes);
            }
            if (typeof(global::LightSwitchApplication.SocialRel) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SocialRel);
            }
            return null;
        }
    }
}
