//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShuData
{
    using System;
    using System.Collections.Generic;
    
    public partial class shu_teacher_all
    {
        public string GH { get; set; }
        public string name { get; set; }
        public string codesex { get; set; }
        public string sex { get; set; }
        public string codenation { get; set; }
        public string nation { get; set; }
        public string sfz { get; set; }
        public string birthday { get; set; }
        public string JXRQ { get; set; }
        public string CJGZRQ { get; set; }
        public string codepoli { get; set; }
        public string poli { get; set; }
        public string polidata { get; set; }
        public string codestaffgroup { get; set; }
        public string staffgroup { get; set; }
        public string codestaffsubgroup { get; set; }
        public string staffsubgroup { get; set; }
        public string codedepartment { get; set; }
        public string codedepartment2 { get; set; }
        public string department { get; set; }
        public string department2 { get; set; }
        public string codeedu { get; set; }
        public string education { get; set; }
        public string college { get; set; }
        public string xw { get; set; }
        public string codezc { get; set; }
        public string zc { get; set; }
        public string zw { get; set; }
        public string codezj { get; set; }
        public string zj { get; set; }
        public string xk { get; set; }
    }
}
