//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LightSwitchApplication", "SocialRel_Infoes", "Infoes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Infoes), "SocialRel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.SocialRel), true)]

#endregion

namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApplicationData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApplicationData object using the connection string found in the 'ApplicationData' section of the application configuration file.
        /// </summary>
        public ApplicationData() : base("name=ApplicationData", "ApplicationData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        public ApplicationData(string connectionString) : base(connectionString, "ApplicationData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        public ApplicationData(EntityConnection connection) : base(connection, "ApplicationData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Infoes> InfoesSet
        {
            get
            {
                if ((_InfoesSet == null))
                {
                    _InfoesSet = base.CreateObjectSet<Infoes>("InfoesSet");
                }
                return _InfoesSet;
            }
        }
        private ObjectSet<Infoes> _InfoesSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SocialRel> SocialRels
        {
            get
            {
                if ((_SocialRels == null))
                {
                    _SocialRels = base.CreateObjectSet<SocialRel>("SocialRels");
                }
                return _SocialRels;
            }
        }
        private ObjectSet<SocialRel> _SocialRels;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InfoesSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInfoesSet(Infoes infoes)
        {
            base.AddObject("InfoesSet", infoes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SocialRels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSocialRels(SocialRel socialRel)
        {
            base.AddObject("SocialRels", socialRel);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Infoes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Infoes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Infoes object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pID">Initial value of the PID property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static Infoes CreateInfoes(global::System.Int32 id, global::System.String pID, global::System.Byte[] rowVersion)
        {
            Infoes infoes = new Infoes();
            infoes.Id = id;
            infoes.PID = pID;
            infoes.RowVersion = rowVersion;
            return infoes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PID
        {
            get
            {
                return _PID;
            }
            set
            {
                OnPIDChanging(value);
                ReportPropertyChanging("PID");
                _PID = value;
                ReportPropertyChanged("PID");
                OnPIDChanged();
            }
        }
        private global::System.String _PID;
        partial void OnPIDChanging(global::System.String value);
        partial void OnPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo);
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = value;
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.Byte[] _Photo;
        partial void OnPhotoChanging(global::System.Byte[] value);
        partial void OnPhotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = value;
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = value;
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.String _Sex;
        partial void OnSexChanging(global::System.String value);
        partial void OnSexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                OnBirthDateChanging(value);
                ReportPropertyChanging("BirthDate");
                _BirthDate = value;
                ReportPropertyChanged("BirthDate");
                OnBirthDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BirthDate;
        partial void OnBirthDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nation
        {
            get
            {
                return _Nation;
            }
            set
            {
                OnNationChanging(value);
                ReportPropertyChanging("Nation");
                _Nation = value;
                ReportPropertyChanged("Nation");
                OnNationChanged();
            }
        }
        private global::System.String _Nation;
        partial void OnNationChanging(global::System.String value);
        partial void OnNationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Native
        {
            get
            {
                return _Native;
            }
            set
            {
                OnNativeChanging(value);
                ReportPropertyChanging("Native");
                _Native = value;
                ReportPropertyChanged("Native");
                OnNativeChanged();
            }
        }
        private global::System.String _Native;
        partial void OnNativeChanging(global::System.String value);
        partial void OnNativeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Politics
        {
            get
            {
                return _Politics;
            }
            set
            {
                OnPoliticsChanging(value);
                ReportPropertyChanging("Politics");
                _Politics = value;
                ReportPropertyChanged("Politics");
                OnPoliticsChanged();
            }
        }
        private global::System.String _Politics;
        partial void OnPoliticsChanging(global::System.String value);
        partial void OnPoliticsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Health
        {
            get
            {
                return _Health;
            }
            set
            {
                OnHealthChanging(value);
                ReportPropertyChanging("Health");
                _Health = value;
                ReportPropertyChanged("Health");
                OnHealthChanged();
            }
        }
        private global::System.String _Health;
        partial void OnHealthChanging(global::System.String value);
        partial void OnHealthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProJob
        {
            get
            {
                return _ProJob;
            }
            set
            {
                OnProJobChanging(value);
                ReportPropertyChanging("ProJob");
                _ProJob = value;
                ReportPropertyChanged("ProJob");
                OnProJobChanged();
            }
        }
        private global::System.String _ProJob;
        partial void OnProJobChanging(global::System.String value);
        partial void OnProJobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Speciality
        {
            get
            {
                return _Speciality;
            }
            set
            {
                OnSpecialityChanging(value);
                ReportPropertyChanging("Speciality");
                _Speciality = value;
                ReportPropertyChanged("Speciality");
                OnSpecialityChanged();
            }
        }
        private global::System.String _Speciality;
        partial void OnSpecialityChanging(global::System.String value);
        partial void OnSpecialityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthPlace
        {
            get
            {
                return _BirthPlace;
            }
            set
            {
                OnBirthPlaceChanging(value);
                ReportPropertyChanging("BirthPlace");
                _BirthPlace = value;
                ReportPropertyChanged("BirthPlace");
                OnBirthPlaceChanged();
            }
        }
        private global::System.String _BirthPlace;
        partial void OnBirthPlaceChanging(global::System.String value);
        partial void OnBirthPlaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> WorkDate
        {
            get
            {
                return _WorkDate;
            }
            set
            {
                OnWorkDateChanging(value);
                ReportPropertyChanging("WorkDate");
                _WorkDate = value;
                ReportPropertyChanged("WorkDate");
                OnWorkDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _WorkDate;
        partial void OnWorkDateChanging(Nullable<global::System.DateTime> value);
        partial void OnWorkDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PartyDate
        {
            get
            {
                return _PartyDate;
            }
            set
            {
                OnPartyDateChanging(value);
                ReportPropertyChanging("PartyDate");
                _PartyDate = value;
                ReportPropertyChanged("PartyDate");
                OnPartyDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PartyDate;
        partial void OnPartyDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPartyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Duty
        {
            get
            {
                return _Duty;
            }
            set
            {
                OnDutyChanging(value);
                ReportPropertyChanging("Duty");
                _Duty = value;
                ReportPropertyChanged("Duty");
                OnDutyChanged();
            }
        }
        private global::System.String _Duty;
        partial void OnDutyChanging(global::System.String value);
        partial void OnDutyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rank
        {
            get
            {
                return _Rank;
            }
            set
            {
                OnRankChanging(value);
                ReportPropertyChanging("Rank");
                _Rank = value;
                ReportPropertyChanged("Rank");
                OnRankChanged();
            }
        }
        private global::System.String _Rank;
        partial void OnRankChanging(global::System.String value);
        partial void OnRankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JobTitle
        {
            get
            {
                return _JobTitle;
            }
            set
            {
                OnJobTitleChanging(value);
                ReportPropertyChanging("JobTitle");
                _JobTitle = value;
                ReportPropertyChanged("JobTitle");
                OnJobTitleChanged();
            }
        }
        private global::System.String _JobTitle;
        partial void OnJobTitleChanging(global::System.String value);
        partial void OnJobTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Major
        {
            get
            {
                return _Major;
            }
            set
            {
                OnMajorChanging(value);
                ReportPropertyChanging("Major");
                _Major = value;
                ReportPropertyChanged("Major");
                OnMajorChanged();
            }
        }
        private global::System.String _Major;
        partial void OnMajorChanging(global::System.String value);
        partial void OnMajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Character
        {
            get
            {
                return _Character;
            }
            set
            {
                OnCharacterChanging(value);
                ReportPropertyChanging("Character");
                _Character = value;
                ReportPropertyChanged("Character");
                OnCharacterChanged();
            }
        }
        private global::System.String _Character;
        partial void OnCharacterChanging(global::System.String value);
        partial void OnCharacterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Interest
        {
            get
            {
                return _Interest;
            }
            set
            {
                OnInterestChanging(value);
                ReportPropertyChanging("Interest");
                _Interest = value;
                ReportPropertyChanged("Interest");
                OnInterestChanged();
            }
        }
        private global::System.String _Interest;
        partial void OnInterestChanging(global::System.String value);
        partial void OnInterestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String XianRen
        {
            get
            {
                return _XianRen;
            }
            set
            {
                OnXianRenChanging(value);
                ReportPropertyChanging("XianRen");
                _XianRen = value;
                ReportPropertyChanged("XianRen");
                OnXianRenChanged();
            }
        }
        private global::System.String _XianRen;
        partial void OnXianRenChanging(global::System.String value);
        partial void OnXianRenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NiRen
        {
            get
            {
                return _NiRen;
            }
            set
            {
                OnNiRenChanging(value);
                ReportPropertyChanging("NiRen");
                _NiRen = value;
                ReportPropertyChanged("NiRen");
                OnNiRenChanged();
            }
        }
        private global::System.String _NiRen;
        partial void OnNiRenChanging(global::System.String value);
        partial void OnNiRenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NiMian
        {
            get
            {
                return _NiMian;
            }
            set
            {
                OnNiMianChanging(value);
                ReportPropertyChanging("NiMian");
                _NiMian = value;
                ReportPropertyChanged("NiMian");
                OnNiMianChanged();
            }
        }
        private global::System.String _NiMian;
        partial void OnNiMianChanging(global::System.String value);
        partial void OnNiMianChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkExp
        {
            get
            {
                return _WorkExp;
            }
            set
            {
                OnWorkExpChanging(value);
                ReportPropertyChanging("WorkExp");
                _WorkExp = value;
                ReportPropertyChanged("WorkExp");
                OnWorkExpChanged();
            }
        }
        private global::System.String _WorkExp;
        partial void OnWorkExpChanging(global::System.String value);
        partial void OnWorkExpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RewardPunish
        {
            get
            {
                return _RewardPunish;
            }
            set
            {
                OnRewardPunishChanging(value);
                ReportPropertyChanging("RewardPunish");
                _RewardPunish = value;
                ReportPropertyChanged("RewardPunish");
                OnRewardPunishChanged();
            }
        }
        private global::System.String _RewardPunish;
        partial void OnRewardPunishChanging(global::System.String value);
        partial void OnRewardPunishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exam
        {
            get
            {
                return _Exam;
            }
            set
            {
                OnExamChanging(value);
                ReportPropertyChanging("Exam");
                _Exam = value;
                ReportPropertyChanged("Exam");
                OnExamChanged();
            }
        }
        private global::System.String _Exam;
        partial void OnExamChanging(global::System.String value);
        partial void OnExamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reason
        {
            get
            {
                return _Reason;
            }
            set
            {
                OnReasonChanging(value);
                ReportPropertyChanging("Reason");
                _Reason = value;
                ReportPropertyChanged("Reason");
                OnReasonChanged();
            }
        }
        private global::System.String _Reason;
        partial void OnReasonChanging(global::System.String value);
        partial void OnReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullEdu
        {
            get
            {
                return _FullEdu;
            }
            set
            {
                OnFullEduChanging(value);
                ReportPropertyChanging("FullEdu");
                _FullEdu = value;
                ReportPropertyChanged("FullEdu");
                OnFullEduChanged();
            }
        }
        private global::System.String _FullEdu;
        partial void OnFullEduChanging(global::System.String value);
        partial void OnFullEduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FUniMajor
        {
            get
            {
                return _FUniMajor;
            }
            set
            {
                OnFUniMajorChanging(value);
                ReportPropertyChanging("FUniMajor");
                _FUniMajor = value;
                ReportPropertyChanged("FUniMajor");
                OnFUniMajorChanged();
            }
        }
        private global::System.String _FUniMajor;
        partial void OnFUniMajorChanging(global::System.String value);
        partial void OnFUniMajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PartEdu
        {
            get
            {
                return _PartEdu;
            }
            set
            {
                OnPartEduChanging(value);
                ReportPropertyChanging("PartEdu");
                _PartEdu = value;
                ReportPropertyChanged("PartEdu");
                OnPartEduChanged();
            }
        }
        private global::System.String _PartEdu;
        partial void OnPartEduChanging(global::System.String value);
        partial void OnPartEduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PUniMajor
        {
            get
            {
                return _PUniMajor;
            }
            set
            {
                OnPUniMajorChanging(value);
                ReportPropertyChanging("PUniMajor");
                _PUniMajor = value;
                ReportPropertyChanged("PUniMajor");
                OnPUniMajorChanged();
            }
        }
        private global::System.String _PUniMajor;
        partial void OnPUniMajorChanging(global::System.String value);
        partial void OnPUniMajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "SocialRel_Infoes", "SocialRel")]
        public EntityCollection<SocialRel> SocialRel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SocialRel>("LightSwitchApplication.SocialRel_Infoes", "SocialRel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SocialRel>("LightSwitchApplication.SocialRel_Infoes", "SocialRel", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="SocialRel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SocialRel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SocialRel object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="relTitle">Initial value of the RelTitle property.</param>
        /// <param name="relName">Initial value of the RelName property.</param>
        /// <param name="relBirthDate">Initial value of the RelBirthDate property.</param>
        /// <param name="chuJiRel_ChuJiInfoes1">Initial value of the ChuJiRel_ChuJiInfoes1 property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static SocialRel CreateSocialRel(global::System.Int32 id, global::System.String relTitle, global::System.String relName, global::System.String relBirthDate, global::System.Int32 chuJiRel_ChuJiInfoes1, global::System.Byte[] rowVersion)
        {
            SocialRel socialRel = new SocialRel();
            socialRel.Id = id;
            socialRel.RelTitle = relTitle;
            socialRel.RelName = relName;
            socialRel.RelBirthDate = relBirthDate;
            socialRel.ChuJiRel_ChuJiInfoes1 = chuJiRel_ChuJiInfoes1;
            socialRel.RowVersion = rowVersion;
            return socialRel;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RelTitle
        {
            get
            {
                return _RelTitle;
            }
            set
            {
                OnRelTitleChanging(value);
                ReportPropertyChanging("RelTitle");
                _RelTitle = value;
                ReportPropertyChanged("RelTitle");
                OnRelTitleChanged();
            }
        }
        private global::System.String _RelTitle;
        partial void OnRelTitleChanging(global::System.String value);
        partial void OnRelTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RelName
        {
            get
            {
                return _RelName;
            }
            set
            {
                OnRelNameChanging(value);
                ReportPropertyChanging("RelName");
                _RelName = value;
                ReportPropertyChanged("RelName");
                OnRelNameChanged();
            }
        }
        private global::System.String _RelName;
        partial void OnRelNameChanging(global::System.String value);
        partial void OnRelNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RelBirthDate
        {
            get
            {
                return _RelBirthDate;
            }
            set
            {
                OnRelBirthDateChanging(value);
                ReportPropertyChanging("RelBirthDate");
                _RelBirthDate = value;
                ReportPropertyChanged("RelBirthDate");
                OnRelBirthDateChanged();
            }
        }
        private global::System.String _RelBirthDate;
        partial void OnRelBirthDateChanging(global::System.String value);
        partial void OnRelBirthDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RelParty
        {
            get
            {
                return _RelParty;
            }
            set
            {
                OnRelPartyChanging(value);
                ReportPropertyChanging("RelParty");
                _RelParty = value;
                ReportPropertyChanged("RelParty");
                OnRelPartyChanged();
            }
        }
        private global::System.String _RelParty;
        partial void OnRelPartyChanging(global::System.String value);
        partial void OnRelPartyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RelComJob
        {
            get
            {
                return _RelComJob;
            }
            set
            {
                OnRelComJobChanging(value);
                ReportPropertyChanging("RelComJob");
                _RelComJob = value;
                ReportPropertyChanged("RelComJob");
                OnRelComJobChanged();
            }
        }
        private global::System.String _RelComJob;
        partial void OnRelComJobChanging(global::System.String value);
        partial void OnRelComJobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChuJiRel_ChuJiInfoes1
        {
            get
            {
                return _ChuJiRel_ChuJiInfoes1;
            }
            set
            {
                OnChuJiRel_ChuJiInfoes1Changing(value);
                ReportPropertyChanging("ChuJiRel_ChuJiInfoes1");
                _ChuJiRel_ChuJiInfoes1 = value;
                ReportPropertyChanged("ChuJiRel_ChuJiInfoes1");
                OnChuJiRel_ChuJiInfoes1Changed();
            }
        }
        private global::System.Int32 _ChuJiRel_ChuJiInfoes1;
        partial void OnChuJiRel_ChuJiInfoes1Changing(global::System.Int32 value);
        partial void OnChuJiRel_ChuJiInfoes1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "SocialRel_Infoes", "Infoes")]
        public Infoes Infoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infoes>("LightSwitchApplication.SocialRel_Infoes", "Infoes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infoes>("LightSwitchApplication.SocialRel_Infoes", "Infoes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Infoes> InfoesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infoes>("LightSwitchApplication.SocialRel_Infoes", "Infoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Infoes>("LightSwitchApplication.SocialRel_Infoes", "Infoes", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
