//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_Inserting(global::LightSwitchApplication.Infoes entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_Inserted(global::LightSwitchApplication.Infoes entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_Updating(global::LightSwitchApplication.Infoes entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_Updated(global::LightSwitchApplication.Infoes entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_Deleting(global::LightSwitchApplication.Infoes entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_Deleted(global::LightSwitchApplication.Infoes entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_Validate(global::LightSwitchApplication.Infoes entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InfoesSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Infoes, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_Inserting(global::LightSwitchApplication.SocialRel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_Inserted(global::LightSwitchApplication.SocialRel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_Updating(global::LightSwitchApplication.SocialRel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_Updated(global::LightSwitchApplication.SocialRel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_Deleting(global::LightSwitchApplication.SocialRel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_Deleted(global::LightSwitchApplication.SocialRel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_Validate(global::LightSwitchApplication.SocialRel entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRels_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SocialRel, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationData_InitializingConnection(global::Microsoft.LightSwitch.DatabaseConnectionState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Infoes>
                __InfoesSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Infoes>(
                    "InfoesSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__InfoesSet_Filter);
            private static bool __InfoesSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.InfoesSet_CanInsert(ref result);
                return result;
            }
            private static bool __InfoesSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.InfoesSet_CanUpdate(ref result);
                return result;
            }
            private static bool __InfoesSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.InfoesSet_CanDelete(ref result);
                return result;
            }
            private static bool __InfoesSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.InfoesSet_CanRead(ref result);
                return result;
            }
            private static void __InfoesSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Infoes e)
            {
                d.InfoesSet_Inserting(e);
            }
            private static void __InfoesSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Infoes e)
            {
                d.InfoesSet_Inserted(e);
            }
            private static void __InfoesSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Infoes e)
            {
                d.InfoesSet_Updating(e);
            }
            private static void __InfoesSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Infoes e)
            {
                d.InfoesSet_Updated(e);
            }
            private static void __InfoesSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Infoes e)
            {
                d.InfoesSet_Deleting(e);
            }
            private static void __InfoesSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Infoes e)
            {
                d.InfoesSet_Deleted(e);
            }
            private static void __InfoesSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Infoes e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.InfoesSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Infoes, bool>> __InfoesSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Infoes, bool>> filter = null;
                d.InfoesSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.SocialRel>
                __SocialRelsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.SocialRel>(
                    "SocialRels",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SocialRels_Filter);
            private static bool __SocialRels_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.SocialRels_CanInsert(ref result);
                return result;
            }
            private static bool __SocialRels_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.SocialRels_CanUpdate(ref result);
                return result;
            }
            private static bool __SocialRels_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.SocialRels_CanDelete(ref result);
                return result;
            }
            private static bool __SocialRels_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.SocialRels_CanRead(ref result);
                return result;
            }
            private static void __SocialRels_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SocialRel e)
            {
                d.SocialRels_Inserting(e);
            }
            private static void __SocialRels_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SocialRel e)
            {
                d.SocialRels_Inserted(e);
            }
            private static void __SocialRels_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SocialRel e)
            {
                d.SocialRels_Updating(e);
            }
            private static void __SocialRels_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SocialRel e)
            {
                d.SocialRels_Updated(e);
            }
            private static void __SocialRels_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SocialRel e)
            {
                d.SocialRels_Deleting(e);
            }
            private static void __SocialRels_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SocialRel e)
            {
                d.SocialRels_Deleted(e);
            }
            private static void __SocialRels_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.SocialRels_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SocialRel, bool>> __SocialRels_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SocialRel, bool>> filter = null;
                d.SocialRels_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>
                ___DatabaseAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ApplicationData_InitializingConnection);
            private static void __ApplicationData_InitializingConnection(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.DatabaseConnectionState state)
            {
                d.ApplicationData_InitializingConnection(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
