

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class SocialRel : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the SocialRel entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SocialRel()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SocialRel(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SocialRel> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.SocialRel.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRel_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SocialRel_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.SocialRel.DetailsClass.SetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RelTitle
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelTitle);
            }
            set
            {
                global::LightSwitchApplication.SocialRel.DetailsClass.SetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelTitle, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelTitle_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelTitle_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelTitle_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RelName
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelName);
            }
            set
            {
                global::LightSwitchApplication.SocialRel.DetailsClass.SetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RelBirthDate
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelBirthDate);
            }
            set
            {
                global::LightSwitchApplication.SocialRel.DetailsClass.SetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelBirthDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelBirthDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelBirthDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelBirthDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RelParty
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelParty);
            }
            set
            {
                global::LightSwitchApplication.SocialRel.DetailsClass.SetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelParty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelParty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelParty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelParty_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RelComJob
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelComJob);
            }
            set
            {
                global::LightSwitchApplication.SocialRel.DetailsClass.SetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelComJob, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelComJob_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelComJob_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelComJob_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.SocialRel.DetailsClass.SetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Infoes Infoes
        {
            get
            {
                return global::LightSwitchApplication.SocialRel.DetailsClass.GetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Infoes);
            }
            set
            {
                global::LightSwitchApplication.SocialRel.DetailsClass.SetValue(this, global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Infoes, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Infoes_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Infoes_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Infoes_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.SocialRel,
                global::LightSwitchApplication.SocialRel.DetailsClass,
                global::LightSwitchApplication.SocialRel.DetailsClass.IImplementation,
                global::LightSwitchApplication.SocialRel.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass>.Entry
                __SocialRelEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass>.Entry(
                    global::LightSwitchApplication.SocialRel.DetailsClass.__SocialRel_CreateNew,
                    global::LightSwitchApplication.SocialRel.DetailsClass.__SocialRel_Created,
                    global::LightSwitchApplication.SocialRel.DetailsClass.__SocialRel_AllowSaveWithErrors);
            private static global::LightSwitchApplication.SocialRel __SocialRel_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SocialRel> es)
            {
                return new global::LightSwitchApplication.SocialRel(es);
            }
            private static void __SocialRel_Created(global::LightSwitchApplication.SocialRel e)
            {
                e.SocialRel_Created();
            }
            private static bool __SocialRel_AllowSaveWithErrors(global::LightSwitchApplication.SocialRel e)
            {
                bool result = false;
                e.SocialRel_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.SocialRel.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string> RelTitle
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelTitle) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string> RelName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string> RelBirthDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelBirthDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string> RelParty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelParty) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string> RelComJob
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RelComJob) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::LightSwitchApplication.Infoes> Infoes
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Infoes) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::LightSwitchApplication.Infoes>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string RelTitle { get; set; }
                new string RelName { get; set; }
                new string RelBirthDate { get; set; }
                new string RelParty { get; set; }
                new string RelComJob { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Infoes { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, int>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry
                    RelTitle = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry(
                        "RelTitle",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelTitle_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelTitle_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelTitle_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelTitle_GetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelTitle_SetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelTitle_OnValueChanged);
                private static void _RelTitle_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._RelTitle, sf);
                }
                private static bool _RelTitle_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.RelTitle_IsReadOnly(ref result);
                    return result;
                }
                private static void _RelTitle_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RelTitle_Validate(r);
                }
                private static string _RelTitle_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.RelTitle;
                }
                private static void _RelTitle_SetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RelTitle = v;
                }
                private static void _RelTitle_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.RelTitle_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry
                    RelName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry(
                        "RelName",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelName_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelName_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelName_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelName_GetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelName_SetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelName_OnValueChanged);
                private static void _RelName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._RelName, sf);
                }
                private static bool _RelName_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.RelName_IsReadOnly(ref result);
                    return result;
                }
                private static void _RelName_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RelName_Validate(r);
                }
                private static string _RelName_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.RelName;
                }
                private static void _RelName_SetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RelName = v;
                }
                private static void _RelName_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.RelName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry
                    RelBirthDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry(
                        "RelBirthDate",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelBirthDate_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelBirthDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelBirthDate_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelBirthDate_GetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelBirthDate_SetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelBirthDate_OnValueChanged);
                private static void _RelBirthDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._RelBirthDate, sf);
                }
                private static bool _RelBirthDate_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.RelBirthDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _RelBirthDate_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RelBirthDate_Validate(r);
                }
                private static string _RelBirthDate_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.RelBirthDate;
                }
                private static void _RelBirthDate_SetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RelBirthDate = v;
                }
                private static void _RelBirthDate_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.RelBirthDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry
                    RelParty = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry(
                        "RelParty",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelParty_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelParty_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelParty_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelParty_GetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelParty_SetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelParty_OnValueChanged);
                private static void _RelParty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._RelParty, sf);
                }
                private static bool _RelParty_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.RelParty_IsReadOnly(ref result);
                    return result;
                }
                private static void _RelParty_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RelParty_Validate(r);
                }
                private static string _RelParty_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.RelParty;
                }
                private static void _RelParty_SetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RelParty = v;
                }
                private static void _RelParty_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.RelParty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry
                    RelComJob = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry(
                        "RelComJob",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelComJob_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelComJob_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelComJob_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelComJob_GetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelComJob_SetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RelComJob_OnValueChanged);
                private static void _RelComJob_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._RelComJob, sf);
                }
                private static bool _RelComJob_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.RelComJob_IsReadOnly(ref result);
                    return result;
                }
                private static void _RelComJob_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RelComJob_Validate(r);
                }
                private static string _RelComJob_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.RelComJob;
                }
                private static void _RelComJob_SetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RelComJob = v;
                }
                private static void _RelComJob_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.RelComJob_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::LightSwitchApplication.Infoes>.Entry
                    Infoes = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::LightSwitchApplication.Infoes>.Entry(
                        "Infoes",
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Infoes_Stub,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Infoes_ComputeIsReadOnly,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Infoes_Validate,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Infoes_GetCoreImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Infoes_GetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Infoes_SetImplementationValue,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Infoes_Refresh,
                        global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties._Infoes_OnValueChanged);
                private static void _Infoes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SocialRel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::LightSwitchApplication.Infoes>.Data> c, global::LightSwitchApplication.SocialRel.DetailsClass d, object sf)
                {
                    c(d, ref d._Infoes, sf);
                }
                private static bool _Infoes_ComputeIsReadOnly(global::LightSwitchApplication.SocialRel e)
                {
                    bool result = false;
                    e.Infoes_IsReadOnly(ref result);
                    return result;
                }
                private static void _Infoes_Validate(global::LightSwitchApplication.SocialRel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Infoes_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Infoes_GetCoreImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.ImplementationEntity.Infoes;
                }
                private static global::LightSwitchApplication.Infoes _Infoes_GetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Infoes, global::LightSwitchApplication.Infoes.DetailsClass>(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Infoes, ref d._Infoes);
                }
                private static void _Infoes_SetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass d, global::LightSwitchApplication.Infoes v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Infoes, ref d._Infoes, (i, ev) => i.Infoes = ev, v);
                }
                private static void _Infoes_Refresh(global::LightSwitchApplication.SocialRel.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.SocialRel.DetailsClass.PropertySetProperties.Infoes, ref d._Infoes);
                }
                private static void _Infoes_OnValueChanged(global::LightSwitchApplication.SocialRel e)
                {
                    e.Infoes_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data _RelTitle;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data _RelName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data _RelBirthDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data _RelParty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data _RelComJob;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SocialRel, global::LightSwitchApplication.SocialRel.DetailsClass, global::LightSwitchApplication.Infoes>.Data _Infoes;
            
        }
    
        #endregion
    }
    
    #endregion
}
